### ISSUE TITLE
Add character limit to topic and topic description

### ISSUE THREAD

**Issue by hannahkane** [futurechris/punpals#38]
- [x] Add character limitation in validation
- [x] Get lib that updates it real-time
- [x] Get it to update on reload, not just first-browse
- [x] Add to desc as well

**Comment by futurechris** [comment]
Close on this, but having some issues with iron router, reloads, and onRendered.
I'm sure there are simpler solutions but this one feels so clean, if I can just make it reactive.

**Comment by futurechris** [comment]
This solution is a bit lacking in UX - would be nice if the character limit turned red/text turned red when it was going to be truncated. Creating this as an issue.
